### PR TITLE
Add /count endpoints

### PR DESCRIPTION
**Pull request by acabunoc**
* addresses #95 

@Alicole - does this address your comments in #95?

### CODE REVIEW

**Comment by acabunoc** [comment]
@aid29 & @guahanweb -- I think the two of your are most familiar with this section. Could one of you review / let me know if there's a smarter way to do this?

Many thanks :)

**Comment by guahanweb** [comment]
Seems like this is something hefty enough to merit a utility method, perhaps? Or maybe just send an optional parameter to the getBadges method to allow it to return only the count? Let me take a quick peek.

**Comment by guahanweb** [comment]
Meh... after looking a bit more deeply at it, I think you're fine. There is definitely some cleanup we can do within the modules to avoid code duplication, but the actual service is not the most intuitive to work with.

**Comment by acabunoc** [comment]
Thanks for looking into this @guahanweb! :+1: :100: 

@Alicole, let me know if this helps with the snippets issue :)

**Comment by Alicole** [comment]
@acabunoc That's great just tested it with paperbadger.herokuapp.com/papers/10.1186/2047-217X-3-18/badges/count -- and it gave back 50 :+1: 

Is this just a free text or provided as json?

**Comment by acabunoc** [comment]
@Alicole 
It returns the length as JSON:
https://github.com/mozillascience/PaperBadger/blob/e6a3761b72ad734957f72457bdd44a50f0d0fe48/src/routes/papers/index.js#L31

Let me know if that works for you!

**Comment by Alicole** [comment]
@acabunoc Can you please attach an example so we know what to expect.

**Pull request merged**
