### PR TITLE
Fix specs

### PR DESCRIPTION
**Pull request by audy**
Specs were failing b/c tests needed a session cookie and b/c jade wasn't imported in `src/app.js`.

### CODE REVIEW

**Comment by audy** [comment]
P.S. I see the hinting libraries are specified under dependencies as well as devDependencies in `package.json`. Is that intentional? If not, I can remove the duplicates in this PR.

**Comment by acabunoc** [comment]
unintentional! Good catch, thanks

**Comment by audy** [comment]
re 325dcd6 `s/hinting/linting`.

**Comment by acabunoc** [comment]
This is lovely.  r+!

**Pull request merged**
