### PR TITLE
pass environment to client

### PR DESCRIPTION
**Pull request by acabunoc**
* now we can fetch badges properly again!
* not sure why tests were passing without this...

### CODE REVIEW

**Comment by guahanweb** [comment]
cr:gh - LGTM!

**Comment by acabunoc** [comment]
Thanks @guahanweb! (...also, what does cr:gh mean?)

**Comment by guahanweb** [comment]
cr:gh === "Code Review: Garth Henson" :)

-GH

**Comment by acabunoc** [comment]
ahhhhh, thanks :)

**Pull request merged**
