### PR TITLE
lint

### PR DESCRIPTION
**Pull request by acabunoc**
Forgot to npm run lint before I commit last time...

### CODE REVIEW

**Comment by acabunoc** [comment]
@audy can you review? Super simple spacing stuff.

**Comment by audy** [comment]
Appears to be okay. Having an unrelated issue with `config.PORT` being `undefined`. Doesn't appear to have anything to do with this branch, however.

**Comment by acabunoc** [comment]
I think you need to source .env

Thanks!

**Comment by audy** [comment]
oh right. derp.

**Comment by acabunoc** [comment]
To be fair, I think dotenv is supposed to take care of that for you. Might be worthwhile to look into dotenv use. I forgot to test that when I reviewed that section.

**Pull request merged**
