### PR TITLE
upgrading to node 4.4.5; both the docker setup and the deployment set…

### LINKED ISSUE #192: Move to node v4
LTS for 0.12 runs out at the end of the year, so moving to v4 is going to be needed soon.

Upgrading also pulls in newer versions of some of the dependencies, which is good.

Figure out what needs to be done, given that the current instructions are for both running on Docker and locally, and also that the likely deployment target is Heroku.

### PR DESCRIPTION
**Pull request by josmas**
…up for heroku. Closes #192 

We decided to move to node 4 instead of 6, so will close #202 when this one is merged.

### CODE REVIEW

**Comment by acabunoc** [comment]
I'm getting this, not sure why:

>  23 passing (10s)
  1 failing

 > 1) Integration test against the real Badge server get all badges of a certain paper:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

I think saw someone else had this problem in the chat? Works fine for me on master

screen shot 2016-06-03 at 11 37 22

**Comment by acabunoc** [comment]
oh, it might be cause i'm on node 5.9  (I'm sleepy!) will try again :)

**Comment by acabunoc** [comment]
R+! It was my node version 👍

**Comment by josmas** [comment]
Thanks for the review!

Tests timeout at times; I guess the test-api server is slower than prod. I will merge this and separately add an additional couple of seconds to the mocha tests. Especially when the test server has to _wake up_, several tests will timeout the first time they are run.

**Comment by acabunoc** [comment]
You're right! I just tried again with node 5.9 and it works. I guess I was just impatient :)

**Comment by andreabedini** [comment]
I was getting that intermittently too

**Pull request merged**
