### PR TITLE
paper badger widget javascript

### PR DESCRIPTION
**Pull request by Alicole**

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks @Alicole! I'll try this out soon :)

thanks!

**Comment by Alicole** [comment]
To view you'll need the following html snippet:
<div class="badge-container">
        
     <script> 
     var conf={"article-doi": "10.1186/2047-217X-3-18", "class": "badge-container"};
     
     showBadges(conf);
     
     </script>
</div>

Also this currently uses Jquery for AJAX request and binding for widget events.

**Comment by acabunoc** [comment]
Flagging @rcpeters :)

**Comment by acabunoc** [comment]
R+ Thanks :) Merging in

Are you planning on removing the jquery dependency?

**Comment by Alicole** [comment]
We've removed the majority of the dependencies, mostly using pure Javascript now.

Apart from for the AJAX/REST API request and bind event.

Currently looking into alternatives for these too.

**Comment by Alicole** [comment]
@acabunoc -- AJAX helper method committed in place of Jquery .get function.

**Comment by acabunoc** [comment]
Hey @Alicole, this PR was merged in, so we have to make another, sorry!

Are these the changes you're proposing: https://github.com/mozillascience/PaperBadger/compare/master...Alicole:master

It looks like we might be missing a new file?

**Comment by acabunoc** [comment]
Go ahead and make the PR! When I took a look at the changes there now, it showed all deletions and no new changes:

screen shot 2015-09-01 at 10 44 15

Could you take a look when you make the PR? Thanks :)

**Pull request merged**
