### PR TITLE
follow doi spec

### PR DESCRIPTION
**Pull request by acabunoc**
* http://www.apastyle.org/learn/faqs/what-is-doi.aspx
* starts with '10.'
* followed by four or more digits as a prefix
* slash
* suffix assigned by publisher - flexible

### CODE REVIEW

**Comment by acabunoc** [comment]
@audy - can you r? I think these changes are touching a lot of stuff you wrote.

**Comment by acabunoc** [comment]
@audy (when you finish your manuscript stuff. No rush)

**Comment by acabunoc** [comment]
Updated PR with current master!

@audy, are you able to look at this in the next few days? Let me know if you're busy (happy summer!), I can re-assign :)

**Comment by audy** [comment]
Yes. I am finally able to catch up on GitHub!

On Wed, Aug 19, 2015 at 2:48 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Updated PR with current master!
>
> @audy <https://github.com/audy>, are you able to look at this in the next
> few days? Let me know if you're busy (happy summer!), I can re-assign :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/pull/80#issuecomment-132739430>
> .
>



-- 
--austin

**Comment by audy** [comment]
r+

**Comment by acabunoc** [comment]
thanks Austin!

**Pull request merged**
