### PR TITLE
Orcid Auth2

### PR DESCRIPTION
**Pull request by rcpeters**

### CODE REVIEW

**Comment by acabunoc** [comment]
@rcpeters is this ready for review? I'd love to test it out

**Comment by rcpeters** [comment]
I would say merge it. Someone will still need to hook it up to the client.
I don't know enough about reactjs to be effect in this timeframe.


On Thu, Jun 4, 2015 at 11:59 AM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> @rcpeters <https://github.com/rcpeters> is this ready for review? I'd
> love to test it out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/pull/42#issuecomment-109010118>
> .
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by acabunoc** [comment]
I was able to go through the workflow! Really nice :)

Had to set SESSION_SECRET for this to run -- is this documented somewhere?

**Comment by acabunoc** [comment]
I can handle the client stuff :)

**Comment by acabunoc** [comment]
Just saw the SUPER_SECRET stuff you added in the last PR to env.dist. Will merge, update heroku env, then push up to http://paperbadger.herokuapp.com/ soon :)

**Comment by acabunoc** [comment]
@rcpeters -- I set this up with:

    ORCID_REDIRECT_URI=http://paperbadger.herokuapp.com/orcid_auth_callback

Will I need to generate new ORCID_AUTH_CLIENT_ID & ORCID_AUTH_CLIENT_SECRET for this url?

**Comment by rcpeters** [comment]
Awesome to hear you can take care of it. I'm excited to see it working end
to end!

On Thu, Jun 4, 2015 at 12:43 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> I can handle the client stuff :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/pull/42#issuecomment-109026674>
> .
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by acabunoc** [comment]
up and working on http://paperbadger.herokuapp.com/ with the new credentials :) Thanks again @rcpeters!

**Pull request merged**
