### PR TITLE
allow for multiple badges to be issued at once

### PR DESCRIPTION
**Pull request by acabunoc**
* for one author on a paper -- they may have contributed multiple roles

### CODE REVIEW

**Comment by acabunoc** [comment]
Hey @aid29! If you have time, could you review this?

I modified the badge creation endpoint in `app.js` to allow for multiple badges. Because of this, I couldn't use the `returnBadges` function you created. Is there a better way to handle multiple calls to `badgerService.createBadge`?

link to code:
https://github.com/mozillascience/PaperBadger/pull/78/files#diff-bd9c9dcd314f2d7df52935b3a6a4d504R193

**Comment by aid29** [comment]
Hi @acabunoc  i have checked the badgeKit-client-api, they provide 'createBadgeInstances' as well. I think better to use this method to create the multiple badges at one time.

**Comment by acabunoc** [comment]
@aid29 -- good call, I'll try that out

**Comment by acabunoc** [comment]
@aid29 - I did some research on the bulk badge issuing method (`createBadgeInstances`)

Looks like the bulk issuing method in `badgekit-api` / `badgekit-api-client` issues multiple instances of the *same badge* (ie. 20 instances of the **conceptualization** badge to **different users**).

In Paper Badger, authors will claim badges based on their contributions to a paper. We want to be able to issue multiple badges to the same user (ie. the **conceptualization**, **data_curation** and **investigation** badges all to **one user**)


https://github.com/mozilla/badgekit-api/blob/master/app/routes/badge-instances.js#L258

Anyways, I don't think we can use `createBadgeInstances` as is. @aid29, I'd appreciate any other solutions / insight you might have.  Otherwise, I don't know how to improve on this solution.

**Comment by aid29** [comment]
@acabunoc Sorry, I have pointed the wrong direction.
I don't have any ideas now  :-/  part of moving the multi calling logic to inside of badgeService, better for the test and maintenance.

I think the auto tests are important here. If you are not against, I can try to use docker compose to build our dev environment, and we can run our all tests (include the writes tests) locally. This work will relate to #75 #68 #65 

And our Travis CI support docker?

**Comment by acabunoc** [comment]
Do we need docker if we have a test server up and running? 
badgekit-api-test-sciencelab.herokuapp.com/

**Comment by aid29** [comment]
Nice! we got the test environment :)

We can run the tests again badgekit-api-test-sciencelab.herokuapp.com. The data on test env is easy to restore?

But We still need Docker If we want to run our tests on the local dev env.

**Comment by acabunoc** [comment]
@aid29!
Yes, you can run tests on badgekit-api-test-sciencelab.herokuapp.com! 

I'll let you and @audy discuss how we'll run tests -- #75 would be a good place for that discussion.

**Pull request merged**
