### PR TITLE
Pass the ORCID to the view

### PR DESCRIPTION
**Pull request by acabunoc**
* wrap Router.run into App.init so that we can intialize the app with user data
* removed /ORCIDiD, we can get data right from the session
* redirect /issue if not logged in, otherwise, populate orcid field
* kind of hacky but it works

### CODE REVIEW

**Comment by acabunoc** [comment]
Ready for review! Running here: http://paperbadger.herokuapp.com

clicking on /issue will prompt you to log in via ORCID if you haven't logged in already. @rcpeters, if you're around today, care to try it out and review?

**Comment by rcpeters** [comment]
Worked for ME! Next sprint we can have auto suggestions based off DOIs in
the ORCID record :-)

On Fri, Jun 5, 2015 at 6:32 AM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Assigned #48 <https://github.com/mozillascience/PaperBadger/pull/48> to
> @rcpeters <https://github.com/rcpeters>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/pull/48#event-323552625>.
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056

**Comment by JJ** [comment]
This is already done, right?

**Comment by acabunoc** [comment]
@JJ - code is there, looking for someone to review my react code and make sure i'm not making a huge mistake the way i'm passing data to the view :)

**Comment by acabunoc** [comment]
@alicoding says we're good! Merging :)

**Comment by wjrsimpson** [comment]
This is really great!
One very small bug is that if the user clicks 'deny' in ORCID, then they go to a 404 page in PaperBadger. I will make a pull request to fix that!

**Comment by acabunoc** [comment]
thanks for catching that @wjrsimpson :) guess I was bit trigger happy with merging

**Comment by wjrsimpson** [comment]
@acabunoc  My fix is here https://github.com/mozillascience/PaperBadger/pull/51.

**Pull request merged**
