### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jinankjain**
@acabunoc  I had tried to refactor the code but for writing unit test case I need some data that is already present in db so that I could check that test run are successful.

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks @jinankjain! I'll test this out tomorrow and compare with the work in #184 :)

If I forget please ping me!

**Comment by acabunoc** [comment]
Hey @jinankjain, I'd rather we wrote some tests first before I merge this in! Let me know if you need help

**Comment by josmas** [comment]
I am about to open a pull request that adds tests for this refactoring.

I don't think that the changes to the `users/index.js` file add much to the refactoring, though.

**Comment by acabunoc** [comment]
Assigned @josmas to review!

**Comment by josmas** [comment]
@jinankjain I cherry-picked your commit on top of the test changes. It is merged now. Thanks!

**Pull request closed without merging**
