### PR TITLE
Updated the docker setup such that it mounts the local source directo…

### PR DESCRIPTION
**Pull request by jonocodes**
…ry for development instead of building a production image.

### CODE REVIEW

**Comment by acabunoc** [comment]
This looks good to me, but I'm not super familiar with Docker :)

@josmas - I'd like your thoughts here, if you get a chance!

**Comment by josmas** [comment]
hey all,

@jonocodes I am getting the following (which I've never seen before):
```
$ docker-compose build
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options.
All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
```

A quick search points towards differences in version used; these are mine (on Mac 10.11.3):
```
$ docker-compose -v
docker-compose version 1.5.2, build 7240ff3

$ docker -v
Docker version 1.9.1, build a34a1d5
```

Same error with `docker-compose up`. Any ideas? If the changes need a particular version to run, could that be added to the Readme?

**Comment by josmas** [comment]
@jonocodes as usual, just when I hit enter I realised that the docker-compose version is already specified in the Readme... DOH!
Sorry about that! I'll upgrade when I get a chance and give it another go.

**Comment by josmas** [comment]
@acabunoc @jonocodes works nicely after upgrading to docker-compose 1.6

Thanks for the changes!

**Comment by acabunoc** [comment]
Sweet! Thanks @jonocodes & @josmas

**Pull request merged**
