### PR TITLE
Add CSS as suggested by @wizgothic

### PR DESCRIPTION
**Pull request by kinow**
As suggested by @wizgothic, here you go. Should fix issue #151

### CODE REVIEW

**Comment by acabunoc** [comment]
Hey @kinow & @wizgothic!

Thank you so much for this work! This does have a (perhaps intended?) side effect where the footer covers content on the home page (or longer screens). Sorry I didn't think about this more when you first proposed this @wizgothic!

The footer cuts off some text on the badge claim page:
screen shot 2016-02-24 at 23 27 27

If we decide to keep the footer sticky I think we should:
* Add padding at the bottom of the pages so we can see all the content
* Make the footer shorter
* OR Make the footer sticky *only* on the shorter pages (about, issue)

Looking at the page, I'm not sure if a sticky footer is the way to go. Open to thoughts here!

**Comment by acabunoc** [comment]
Wow, sorry this took me 27 days to review. Not sure how this got lost!

**Comment by kinow** [comment]
Good point, makes sense to me :smile: :+1:

**Comment by tomhohenstein** [comment]
Hi Everyone, 

Not sure if you're still working on this issue but we might want to check out the [CSS-Tricks post on sticky footers](https://css-tricks.com/snippets/css/sticky-footer/). I'm still working on getting setup locally but it looks like we'd need to edit the css for .content-wrapper and add a pseudo after element to be the same size as the footer.

**Comment by wizgothic** [comment]
Thank you and sorry for the tardive reply :cry: .
It was indeed supposed to serve as a quick fix solely for the specific sections. We could make use of [flexbox](http://caniuse.com/#feat=flexbox) in order to address to multiple current issues :D.

**Comment by jinankjain** [comment]
@acabunoc @wizgothic @tomhohenstein  My PR #163 Fixes footer problem.

Now if content increases footer dynamically moves down.

**Comment by acabunoc** [comment]
Thanks all for your help getting the work done here!

this issue was addressed in #163 with all the help from this discussion by @jinankjain

**Pull request closed without merging**
