### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by acabunoc**
* bump up widget information
* put Contributing before getting started

### CODE REVIEW

**Comment by janhohner** [comment]
I like the changes you made, but there are 2 problems I see in the "Using Paper Badger" section.
1. The code that should be after the second step of the tutorial how to add it to a web site does not get displayed ("2. Above the closing <body> tag, add" <-- code is in the file but the markdown parser removes it).
2. I think step 3 should not only mention that the container-class key needs changing but also the article-doi key.

**Comment by acabunoc** [comment]
Thanks @janhohner! Great points, I'll address these tomorrow and ping you when I'm ready for another review :)

**Comment by janhohner** [comment]
This looks good now! :+1:

**Comment by acabunoc** [comment]
Yayyy, thanks @janhohner! Merging

**Pull request merged**
