### PR TITLE
Add missing software badge

### PR DESCRIPTION
**Pull request by abbycabs**
- found the missing badge

### CODE REVIEW

**Comment by acabunoc** [comment]
@dbild - I know you were looking at using these assets. Here's the software badge! (I missed this when originally adding the assets)

**Comment by acabunoc** [comment]
@akenall - can you review this? Comments here to let me know if this looks good before I merge these changes in.

Just want to check we actually have all the correct badges added this time :)

This is the complete list of badges we have: https://github.com/mozillascience/PaperBadger/tree/add-software-badge/public/img/badge

**Comment by akenall** [comment]
This looks good to me @acabunoc

Amye Kenall
Associate Publisher
Health Sciences and Open Data
Floor 6, 236 Gray's Inn Road
London, WC1X 8HL
Tel: +44 20 3192 2768
Fax: +44 20 3192 2011
amye.kenall@biomedcentral.com<mailto:amye.kenall@biomedcentral.com>
http://www.gigasciencejournal.com/

Follow BioMed Central:

[cid:image001.jpg@01CB3975.0EFB53E0]<http://twitter.com/BioMedCentral>

[Facebook]<http://www.facebook.com/BioMedCentral>

[cid:image003.jpg@01CB3975.0EFB53E0]<http://www.linkedin.com/groups?gid=2807240>

[YouTube]<http://www.youtube.com/user/BioMedCentral>

@OpenDataBMC<https://twitter.com/OpenDataBMC>
@AmyeKenall<https://twitter.com/AmyeKEnall>

**Comment by acabunoc** [comment]
thanks @akenall! :smile:

**Comment by 483426** [comment]
E aí gírias como vai ser

**Pull request merged**
