### PR TITLE
Issue26 

### PR DESCRIPTION
**Pull request by aid29**
- Build BadgeService and refactor the app.js
- Add Integration tests (/test/app.js) which cover all the endpoints in app
(v2)

### CODE REVIEW

**Comment by aid29** [comment]
@acabunoc I have rebased the latest master to my branch issue26 (need to delete the existing issue26 remote) so the old PR for #26 is closed, and this one pass! lol

**Comment by aid29** [comment]
maybe no yet ...

**Comment by acabunoc** [comment]
Hahha, I'll take a look, too ;)

Oh, computers. Always surprising us.

**Comment by aid29** [comment]
Hi @acabunoc Can you check the 4 environment variables are good setup on Travis? I think the error "[ContextError: Missing system]" in the last build https://travis-ci.org/mozillascience/PaperBadger/builds/70191487 cause by the missing of variable BADGES_SYSTEM , thank you.

**Comment by acabunoc** [comment]
Hey @aid29, I'm trying it out now!

I doubled checked the environment variable sin Travis, and they seem to be fine. I ran your code locally and got the same error. Investigating!

**Comment by acabunoc** [comment]
Send a pr to your branch which *may* fix the testing issue -- can you merge it in and we'll see?

**Comment by aid29** [comment]
@acabunoc On my local, it's fine. But when I run "export BADGES_SYSTEM=" on local to empty the variable value. I got the same error as on Travis. "[ContextError: Missing system]"

**Comment by acabunoc** [comment]
It passes on Travis here!:
https://travis-ci.org/mozillascience/PaperBadger/builds/70413354

Merge it in and we can close the pr :)

**Comment by aid29** [comment]
81 build is failed with "Invalid token signature" :(

**Comment by acabunoc** [comment]
So strange... 

It should be the same code running on these both:
https://travis-ci.org/mozillascience/PaperBadger/builds/70413354
https://travis-ci.org/mozillascience/PaperBadger/builds/70415606

**Comment by aid29** [comment]
we have this output in the successful build 
Setting environment variables from repository settings
$ export SESSION_SECRET=[secure]
$ export BADGES_SYSTEM=[secure]
$ export BADGES_KEY=[secure]
$ export BADGES_ENDPOINT=[secure]
$ export BADGES_SECRET=[secure]

but the failed build don't have, there should be the reason.but what is different on the config of Travis?

**Comment by aid29** [comment]
the worker of Travis are different...

**Comment by aid29** [comment]
@acabunoc  Any check can do in your side with Travis?

**Pull request merged**
