### PR TITLE
#26 - integration tests for API

### PR DESCRIPTION
**Pull request by aid29**
- Build BadgeService and refactor the app.js
- Add Integration tests (/test/app.js) which cover all the endpoints in app

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks for the PR @aid29! I'll take a deeper look this weekend / next week -- sorry if it takes me longer than normal, there's a mozilla work week next week and things are a bit hectic :)

@audy - I'd appreciate any comments you have on this, too!

**Comment by aid29** [comment]
@acabunoc No problem at all. Take your time. I'm in holiday next week, if you have any questions, we can park this one until I'm back. Cheers!

**Comment by acabunoc** [comment]
Hey @aid29! Thanks for your patience, hope you had a good break! Are you free to chat this week? I'm free all day tomorrow (EDT) It's a rather large pr, and it would probably help if I had you around to ask questions ;)

@audy -- it might be nice to have you join the call so we can solidify what approach we're taking for testing

**Comment by audy** [comment]
I still need to take a look at this. I am pretty much free any time
tomorrow for a call. LMK what time works.

On Wed, Jul 1, 2015 at 4:14 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> Hey @aid29 <https://github.com/aid29>! Thanks for your patience, hope you
> had a good break! Are you free to chat this week? I'm free all day tomorrow
> (EDT) It's a rather large pr, and it would probably help if I had you
> around to ask questions ;)
>
> @audy <https://github.com/audy> -- it might be nice to have you join the
> call so we can solidify what approach we're taking for testing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/pull/61#issuecomment-117812266>
> .
>



-- 
--austin

**Comment by acabunoc** [comment]
I guess this will be short notice for @aid29! I'll start checking my email early in the morning so maybe we can meet in the afternoon, London time. I'll go through the PR in the meantime :)

oh time zones....

**Comment by audy** [comment]
I'm having trouble sorting through all this. Perhaps it would be better to squash into a single commit? Also, @aid29 do tests pass on your end?

**Comment by audy** [comment]
I squashed it on my end and made a few comments. Before merging, I would squash this into a single commit; remove commented-out code completely and figure out why tests aren't running (seems to have something to do with `config` in `badgeClient.js`.

Then I'll take another look. The changes definitely cleaned up `app.js`.

**Comment by acabunoc** [comment]
Thanks Austin! +1 squash. I'll take a closer look later tonight

**Comment by aid29** [comment]
@acabunoc @audy I can join you guys for the chat today at 9~10 pm London time => at your afternoon 4~5pm. This timing is ok for everyone?

**Comment by acabunoc** [comment]
@aid29 - thanks that works great for me! @audy, I hope you can make it. If not, we have a bunch of your comments, very helpful thanks!

**Comment by audy** [comment]
4-6pm EST should work for me.

On Thu, Jul 2, 2015 at 9:37 AM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> @aid29 <https://github.com/aid29> - thanks that works great for me! @audy
> <https://github.com/audy>, I hope you can make it. If not, we have a
> bunch of your comments, very helpful thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/PaperBadger/pull/61#issuecomment-118036236>
> .
>



-- 
--austin

**Comment by acabunoc** [comment]
hey @audy, you around?

**Comment by aid29** [comment]
@acabunoc how can I trigger the build on CI? It's not auto trigger for pull request on the fork?

**Comment by acabunoc** [comment]
@aid29 -- not sure, it's always run automagically for me. Strange..

**Comment by acabunoc** [comment]
http://blog.travis-ci.com/2014-05-12-why-is-my-build-not-running/

**Comment by audy** [comment]
I just realized you can view all of the changes "squashed"  by going to https://github.com/mozillascience/PaperBadger/pull/61/files.

**Comment by audy** [comment]
For some reason, that last commit didn't make it to Travis. Maybe poke it with a dummy commit?

**Comment by acabunoc** [comment]
Did some digging, looks like the last commit that ran on this branch is https://github.com/mozillascience/PaperBadger/commit/7941addccb684d4c534e8c39f58be398ed17dbda

Which I don't even see in this PR? Maybe that has something to do with it?

Travis is still mysterious and magical to me.

**Pull request closed without merging**
