### PR TITLE
Restructure helper and fix tests accordingly

### PR DESCRIPTION
**Pull request by guahanweb**

### CODE REVIEW

**Comment by acabunoc** [comment]
I really like this! Much better way to test our helper methods.

@aid29 or @audy -- could you also take a look at this? Make sure I'm not missing something :) (Ai & Austin have done a lot of the work in this part of the code)

I'll assign this to @aid29 for review

**Comment by acabunoc** [comment]
Since this is blocking #90, I'll review if we don't hear from @aid29 by EOD today (ET)

**Comment by guahanweb** [comment]
I believe that I merged this into #90 locally, too, so if this resolves, it should be a seamless inclusion of the other, too.

**Comment by acabunoc** [comment]
@guahanweb - since #90 incorporates the changes from this PR, I'm going to close this one and we'll focus on review for #90 :)

Let me know if there's something unique in this PR that I'm missing!!

**Pull request closed without merging**
