### PR TITLE
Fotter Fixed

### LINKED ISSUE #151: Footer is not sticky (About and Issue)
Confirmed on all devices and browsers.

How to fix this- in main.css:

.footer {
    position:fixed;
    bottom:0;
    background: #111;
}

### PR DESCRIPTION
**Pull request by jinankjain**
Fixes #151

### CODE REVIEW

**Comment by jinankjain** [comment]
@acabunoc Could you please review this ?

**Comment by acabunoc** [comment]
Hi @jinankjain - we're discussing this same change here: https://github.com/mozillascience/PaperBadger/pull/152

Thanks!

**Comment by acabunoc** [comment]
@jinankjain thank you so much! I'm running into one small error when I have a narrower screen size:

screen shot 2016-03-03 at 17 16 07

Any way you make the footer more responsive? Thanks again for updating this!

**Comment by jinankjain** [comment]
@acabunoc That could be fixed by increasing the height of footer I will make the necessary changes

**Comment by jinankjain** [comment]
@acabunoc I fixed that footer now looks fine on every screen phone/laptop

**Comment by acabunoc** [comment]
Hey @jinankjain!

Thanks for the update :)

screen shot 2016-03-04 at 17 12 54

I'm still seeing some misformatted text on mobile sizes -- and having a static height leaves the footer unbalanced. I really don't think having a static height is the way to go -- did you look at the resources shared in the previous pr? https://github.com/mozillascience/PaperBadger/pull/152#issuecomment-188905449

Thanks for your patience here! I really appreciate all your modifications to meet our needs!

**Comment by jinankjain** [comment]
Hey @acabunoc What about this new fix, now I have made height of the footer dynamic with content

**Comment by acabunoc** [comment]
Hey @jinankjain! This looks great! R+ merging :)

Here are some pandas for you:

**Pull request merged**
