### PR TITLE
Code Cleanup and Organization: Routes

### PR DESCRIPTION
**Pull request by guahanweb**
In reading the code, I realized that there is a lot of tribal knowledge with how things work. I am trying to take a few passes at low hanging fruit to organize things a bit more cleanly. There are a couple benefits from modularizing the code a bit more:

1.  Multiple people can have their hands in the code with less risk of merge conflicts
2.  Much more approachable application design
3.  Easier to reuse code and less risk of duplication

Please let me know if you have any concerns with the cleanup I'm doing.

### CODE REVIEW

**Comment by guahanweb** [comment]
Clean test run:
image

**Comment by acabunoc** [comment]
Thanks @guahanweb! We've really been needed something like this. I really appreciate the 'tests passing' pic :)

Going through this today!

**Comment by acabunoc** [comment]
R+ - thank you!

**Comment by acabunoc** [comment]
Forgot to run `npm run lint` before I merged!

**Pull request merged**
