### PR TITLE
Updating lint to use gulp-jshint. This allows auto find of .jshintrc

### PR DESCRIPTION
**Pull request by guahanweb**
rather than having to explicitly configure one. By doing so, we can
have a different config file for tests and only have to define global
variables in the appropriate context.

Additionally, I removed the noop from the test/app.js, since that is
no longer necessary.

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks for this, @guahanweb!

I didn't think of separate .jshint configs before this :) Any specific reason for integrating gulp rather than adding another npm script?

     "jshint": "jshint -c .jshintrc src webpack.config.js", 
     "jshint:test": "jshint -c test/.jshintrc test", 
     "lint": "npm run jsbeautify && npm run jshint && npm run jshint:test && npm run jscs", 


Some background:

We originally set up this project to follow the same workflow as other Mozilla Foundation projects. This let other Mozilla engineers drop in on a familiar setup and contribute a bit easier, so we intentionally didn't use gulp and favoured npm scripts. I don't think one is better than the other, and I'd be up for changing if it's better for the project!

**Comment by guahanweb** [comment]
No reason not to have the separate files and scripts. Just be aware the way the task runner would find the config file to allow for hierarchical overrides that you cannot do by explicitly loading a `.jshintrc`. The only other consideration would be the scalability of the script if you are to add additional paths you need to check. Which is going to be more maintainable?

My practice is just to use Gulp to do build time checks (execute tests, linting, compiling, uglify, etc). It's by no means the only way, but just something out of habit. I'd say let's just follow the recognized Mozilla pattern and just create additional scripts for now unless it becomes unwieldy.

**Comment by guahanweb** [comment]
Just updated the PR to just use the `npm scripts` instead, per your recommendation. 

Thanks!

**Comment by acabunoc** [comment]
Awesome, thank you!

And thanks for your flexibility here :D

**Pull request merged**
