### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by amitkumarj441**
Tried refactoring both functions - getTheBadges and getBadges.

### CODE REVIEW

**Comment by acabunoc** [comment]
Thanks @amitkumarj441! I'll take a look soon and see compare with #183 :)

**Comment by acabunoc** [comment]
Hey @amitkumarj441! Like I said in #183, I'd like to add tests before merging in any refactoring on this. Let me know if you need help!

**Comment by amitkumarj441** [comment]
Hi @acabunoc,

I need some data in db to test this. Please review it.

Thank you
Amit Kumar Jaiswal

**Comment by josmas** [comment]
@amitkumarj441 I am sorry but we are closing this one in favour of #183 + #186 because the code was more complete and already tested. Please let us know if you want to work on something else so we don't duplicate effort. You can catch us either on here or through [Gitter](https://gitter.im/mozillascience/PaperBadger). Thanks for your pull request!

**Pull request closed without merging**
